-- Create a table called 'phones'.
-- Insert the following rows into the 'phones' table: 'name', 'manufacturer', 'price' and 'units_sold'.
-- Goal: Write a query that will select the name of each phone and the total revenue generated by each phone. The total revenue is the product of the price and the units sold. Rename the column that contains the total revenue to 'revenue'.

CREATE TABLE telefones (
    nome text,
    fabricante text,
    preco integer,
    unidadesVendidas integer
);

INSERT INTO telefones (nome, fabricante, preco, unidadesVendidas)
VALUES ('iPhone 6', 'Apple', 649, 1925),
       ('Galaxy S6', 'Samsung', 649, 9436),
       ('Moto X', 'Motorola', 399, 2359),
       ('LG G4', 'LG', 649, 2385),
       ('OnePlus One', 'OnePlus', 299, 7543);

SELECT nome, preco * unidadesVendidas AS receita
FROM telefones;
